name: hiimserge
favicon: null
layout_spectrum: 0.787770981900394
typography_spectrum: 0.6282138219103217
title: CATAPULT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.741076064761728
  lightness: 0.7299900550860912
  saturation: 0.751737511716783
  rhythmicContrast: 0.7889314119238406
purpose: []
